apiVersion: v1
kind: Service
metadata:
  name: userservice
spec:
  selector:
    app: {{ .Release.Name }}-user-service
  ports:
  - name: http
    protocol: TCP
    port: {{ .Values.service.userservice.internalPort }}

---

apiVersion: v1
kind: Service
metadata:
  name: taskservice
spec:
  selector:
    app: {{ .Release.Name }}-task-service
  ports:
  - name: http
    protocol: TCP
    # Not exposing the service to external endpoints
    port: {{ .Values.service.taskservice.internalPort }}

---

apiVersion: v1
kind: Service
metadata:
  name: commentservice
spec:
  selector:
    app: {{ .Release.Name }}-comment-service
  ports:
  - name: http
    protocol: TCP
    port: {{ .Values.service.commentservice.internalPort }}
    targetPort: {{ .Values.service.commentservice.externalPort }}
  type: {{ .Values.service.commentservice.type }}