apiVersion: v1
kind: Service
metadata:
  name: mysql
spec:
  selector:
    app: {{ .Release.Name }}-mysql
  ports:
  - name: http
    protocol: TCP
    port: {{ .Values.service.mysql.internalPort }}

---

apiVersion: v1
kind: Service
metadata:
  name: configserver
spec:
  selector:
    app: {{ .Release.Name }}-config-server
  ports:
  - name: http
    protocol: TCP
    # Not exposing the service to external endpoints
    port: {{ .Values.service.configserver.internalPort }}
  type: {{ .Values.service.configserver.type }}

---

apiVersion: v1
kind: Service
metadata:
  name: eurekaregistry
spec:
  selector:
    app: {{ .Release.Name }}-eurekaregistry
  ports:
  - name: http
    protocol: TCP
    port: {{ .Values.service.eurekaregistry.internalPort }}
    targetPort: {{ .Values.service.eurekaregistry.externalPort }}
  type: {{ .Values.service.eurekaregistry.type }}