configserver: 
  image: anilallewar/basic-config-server
  tag: 0.0.1
  replicaCount: 1
  javaOptions: -Xms256M -Xmx512M
  containerMemoryRequest: 256Mi
  containerMemoryLimit: 512Mi

mysql: 
  image: mysql
  tag: latest
  replicaCount: 1
  containerMemoryRequest: 256Mi
  containerMemoryLimit: 1Gi

eurekaregistry: 
  image: anilallewar/basic-webservice-registry
  tag: 0.0.1
  replicaCount: 1
  javaOptions: -Xms256M -Xmx512M
  containerMemoryRequest: 256Mi
  containerMemoryLimit: 512Mi

zipkinserver: 
  image: anilallewar/basic-zipkin-server
  tag: 0.0.1
  replicaCount: 1
  javaOptions: -Xms256M -Xmx1G
  containerMemoryRequest: 256Mi
  containerMemoryLimit: 1Gi

authserver: 
  image: anilallewar/basic-auth-server
  tag: 0.0.1
  replicaCount: 1
  javaOptions: -Xms256M -Xmx1G
  containerMemoryRequest: 256Mi
  containerMemoryLimit: 1Gi

apigateway:
  image: anilallewar/basic-api-gateway
  tag: 0.0.1
  replicaCount: 1
  javaOptions: -Xms256M -Xmx2G
  containerMemoryRequest: 256Mi
  containerMemoryLimit: 2Gi
  
service:
  configserver:
    type: ClusterIP
    internalPort: 8888
  mysql:
    internalPort: 3306
    rootPassword: password
    database: auth
  eurekaregistry:
    type: LoadBalancer
    externalPort: 8761
    internalPort: 8761
  zipkinserver:
    type: LoadBalancer
    externalPort: 9411
    internalPort: 9411
  authserver:
    type: ClusterIP
    internalPort: 8899
  apigateway:
    type: LoadBalancer
    externalPort: 8765
    internalPort: 8765

image:
  pullPolicy: IfNotPresent

spring:
  activeProfile: docker