configserver: 
  image: anilallewar/basic-config-server
  tag: 0.0.1
  replicaCount: 1

mysql: 
  image: mysql
  tag: latest
  replicaCount: 1

eurekaregistry: 
  image: anilallewar/basic-webservice-registry
  tag: 0.0.1
  replicaCount: 1

image:
  pullPolicy: IfNotPresent

spring:
  activeProfile: docker
  
service:
  configserver:
    type: ClusterIP
    internalPort: 8888
  mysql:
    internalPort: 3306
    rootPassword: root
    database: auth
  eurekaregistry:
    type: ClusterIP
    externalPort: 8761
    internalPort: 8761