apiVersion: apps/v1
kind: Deployment
metadata:
  name: config-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: config-server
  template:
    metadata:
      labels:
        app: config-server
    spec:
      containers:
      - name: config-server
        image: anilallewar/basic-config-server:0.0.1
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8888
          name: "http"