apiVersion: apps/v1
kind: Deployment
metadata:
  name: config-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: config-server
  template:
    metadata:
      labels:
        app: config-server
    spec:
      containers:
      - name: config-server
        image: anilallewar/basic-config-server:0.0.1
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8888
          name: "config-port"
        livenessProbe:
          httpGet:
            path: /health
            port: 8888
          initialDelaySeconds: 10
          periodSeconds: 3
          timeoutSeconds: 2
---
apiVersion: v1
kind: Service
metadata:
  name: config-server-service
spec:
  selector:
    app: config-server
  ports:
  - name: http
    protocol: TCP
    port: 8888
    targetPort: 8888
  type: LoadBalancer