apiVersion: v1
kind: Service
metadata:
  name: config-server-service
spec:
  selector:
    app: config-server
  ports:
  - name: http
    protocol: TCP
    port: {{ .Values.service.config-server.internalPort}}
    targetPort: {{ .Values.service.config-server.internalPort}}
  type: LoadBalancer